### ISSUE TITLE
getRewardAmount() is slow 

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-core#203]
it scales linear:  with the count of staking epochs.

After the coineconomic simulation of 10+ years - it takes very long now - what is a problem with the UI.

maybe we can find a better way to retrieve this information.

possible solutions:
- Automatic Staking
- extending contract by writing the total reward  information in the contracts
- retrieve that information from  DMD DB.

**Comment by cryptonit** [comment]
is change to automatic add rewards to staked ammount instead of make them claimable a solution?
that way rewards distributed each epoch end and we can skip implementing claim rewards in ui
only stake and unstake is of relevance

for user how its visible to him how much his stake did grow then somehow we need to track and show that on ui

but how we handle validator max stake gets beyond 50000

we could just accept that max stake can grow by rewards beyond 50000 but never by fresh staked external 
dmd

**Comment by SurfingNerd** [comment]
readding to staked amount would probably be a solution to that.
tracking in the UI could be done from the data of the DMD DB

**Comment by cryptonit** [comment]
but whats really the issue that we cant see he have rewards to claim or that claiming dont work?

because if its just a timeout issue at calculate the claimable rewards we could just place a u have unclaimed rewards message to many of them to precalculatze the ammount

the real question is work the claiming?

**Comment by SurfingNerd** [comment]
rewards do not exist in this manner anymore, since the change to automatic reward restaking: 
https://github.com/DMDcoin/diamond-contracts-core/issues/43
