### ISSUE TITLE
redesign of the payout fraction

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-core#211]
in the current implementation, beeing the Node Operation does not always pay off extra rewards compared to a delegator.
we have redesign the payout calculation so Node Operators always get's more for their Effords than delegators.

**Comment by cryptonit** [comment]
the goal was 20% of validator rewards get upfront distributed to node operator

the leftover 80% are distributed proportional to the coin ownership (here node operatoprs coins again get their share)

a example of a minimum by node operator but maximum by delegaes filled validator candidate

10000 dmd node operator stake and
40000 dmd dlegated stake (shared between multiple delegated=

would result in

20% upfront to node operator
16% to the node operator because of his 20% of staked coins)
64% to the delegates owning 80% of the staked coins

as a second example 

node operator staked 25000 DMD
delegates together staked also 25000 DMD


20% upfront to node operator
40% to the node operator because of his 50% of staked coins)
40% to the delegates owning 50% of the staked coins

____________________________________

the new system which is close to the whitepaper value of 30% guranteed at minimum stake

is more fair because its same behaving no matter how much coins u did stzake as operator
in old system u need to set up minimum size validators to have maximum benefit

new system give flat a additional reward for the effort set up and maintain a validator

and by this incentive make sure people who have the skill prefer run a own node over delegating

**Comment by SurfingNerd** [comment]
added the term "Pool Owner Reward" to the Glossary.
